export const queryKeys = {
  sessions: ['auth', 'sessions'] as const,
  invitations: ['admin', 'invitations'] as const,
  maintenanceStatus: ['admin', 'maintenance-status'] as const,
  administration: ['admin', 'administration'] as const,
  notificationConfig: ['notifications', 'config'] as const,
  groups: ['groups'] as const,
  group: (groupId: string) => ['groups', groupId] as const,
  groupCandidates: (groupId: string) => ['groups', groupId, 'candidates'] as const,
  groupAdministration: (groupId: string) => ['groups', groupId, 'administration'] as const,
  groupAudit: (groupId: string) => ['groups', groupId, 'audit'] as const,
  groupMembershipInvitations: ['groups', 'membership-invitations'] as const,
  albums: ['albums'] as const,
  album: (albumId: string) => ['albums', albumId] as const,
  photoStorage: ['photos', 'storage'] as const,
  recentPhotos: ['photos', 'recent', 4] as const,
  photosPrefix: ['photos', 'list'] as const,
  photos: (filters: unknown) => ['photos', 'list', filters] as const,
  photoSearchOptions: ['photos', 'search-options'] as const,
  photo: (photoId: string) => ['photos', 'detail', photoId] as const,
  photoTimelinePrefix: ['photos', 'timeline'] as const,
  photoTimeline: (year: number) => ['photos', 'timeline', year] as const,
  photoActivity: (userId: string) => ['photos', 'activity', userId] as const,
  photoTrash: ['photos', 'trash'] as const,
  choreCategories: (groupId: string) => ['groups', groupId, 'chore-categories'] as const,
  choreTasks: (groupId: string) => ['groups', groupId, 'chore-tasks'] as const,
  choreMonthlyReports: (groupId: string) => ['groups', groupId, 'chores-monthly'] as const,
  choreMonthlyReport: (groupId: string, month: string) => ['groups', groupId, 'chores-monthly', month] as const,
  shoppingItems: (groupId: string) => ['groups', groupId, 'shopping-items'] as const,
  shoppingRequests: (groupId: string) => ['groups', groupId, 'shopping-requests'] as const,
  shoppingCategories: (groupId: string) => ['groups', groupId, 'shopping-categories'] as const,
  shoppingTrips: (groupId: string) => ['groups', groupId, 'shopping-trips'] as const,
  shoppingTripHistory: (groupId: string) => ['groups', groupId, 'shopping-trips', 'history'] as const,
  shoppingTrip: (tripId: string) => ['shopping-trips', tripId] as const,
  shoppingStatistics: (groupId: string, fromDate: string, toDate: string) =>
    ['groups', groupId, 'shopping-statistics', fromDate, toDate] as const,
}
