export const queryKeys = {
  sessions: ['auth', 'sessions'] as const,
  invitations: ['admin', 'invitations'] as const,
  maintenanceStatus: ['admin', 'maintenance-status'] as const,
  administration: ['admin', 'administration'] as const,
  notificationConfig: ['notifications', 'config'] as const,
  groups: ['groups'] as const,
  group: (groupId: string) => ['groups', groupId] as const,
  groupCandidates: (groupId: string) => ['groups', groupId, 'candidates'] as const,
  groupAdministration: (groupId: string) => ['groups', groupId, 'administration'] as const,
  groupAudit: (groupId: string) => ['groups', groupId, 'audit'] as const,
  groupMembershipInvitations: ['groups', 'membership-invitations'] as const,
  albums: ['albums'] as const,
  album: (albumId: string) => ['albums', albumId] as const,
  photoStorage: ['photos', 'storage'] as const,
  photosPrefix: ['photos', 'list'] as const,
  photos: (filters: unknown) => ['photos', 'list', filters] as const,
  photo: (photoId: string) => ['photos', 'detail', photoId] as const,
  photoTimeline: (year: number) => ['photos', 'timeline', year] as const,
  photoActivity: (userId: string) => ['photos', 'activity', userId] as const,
  photoTrash: ['photos', 'trash'] as const,
  cleaningTasks: (groupId: string) => ['groups', groupId, 'cleaning-tasks'] as const,
  shoppingItems: (groupId: string) => ['groups', groupId, 'shopping-items'] as const,
}
