"""create complete application schema

Revision ID: 20260715_01
Revises:
Create Date: 2026-07-26 17:39:44.579021

"""

# Alembic's generated calls contain long SQL expressions that are kept explicit for schema fidelity.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260715_01"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrative_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_username", sa.String(length=64), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_administrative_audit_events"),
    )
    op.create_index(
        "ix_administrative_audit_events_created_at_id",
        "administrative_audit_events",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_administrative_audit_events_group_id_created_at",
        "administrative_audit_events",
        ["group_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "album_photos",
        sa.Column("album_id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("album_id", "photo_id", name="pk_album_photos"),
    )
    op.create_index("ix_album_photos_photo_id", "album_photos", ["photo_id"], unique=False)
    op.create_table(
        "albums",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_username", sa.String(length=64), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("cover_photo_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("char_length(title) BETWEEN 1 AND 120", name="ck_albums_title_length"),
        sa.CheckConstraint(
            "description IS NULL OR char_length(description) <= 2000", name="ck_albums_description_length"
        ),
        sa.CheckConstraint("title = btrim(title)", name="ck_albums_title_trimmed"),
        sa.PrimaryKeyConstraint("id", name="pk_albums"),
    )
    op.create_index("ix_albums_created_by_user_id", "albums", ["created_by_user_id"], unique=False)
    op.create_index("ix_albums_group_id", "albums", ["group_id"], unique=False)
    op.create_index(
        "ix_albums_updated_at_id",
        "albums",
        [sa.literal_column("updated_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "maintenance_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(status = 'running' AND finished_at IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL)",
            name="ck_maintenance_runs_finished_at",
        ),
        sa.CheckConstraint(
            "job_type IN ('photo_integrity', 'database_backup', 'secondary_storage_backup', 'trash_purge', 'restore_drill')",
            name="ck_maintenance_runs_job_type",
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'warning', 'failed')", name="ck_maintenance_runs_status"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_maintenance_runs"),
    )
    op.create_index(
        "ix_maintenance_runs_job_type_started_at",
        "maintenance_runs",
        ["job_type", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("system_role", sa.String(length=16), server_default="user", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("system_role IN ('admin', 'user')", name="ck_users_system_role"),
        sa.CheckConstraint("username = lower(username)", name="ck_users_username_lowercase"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )
    op.create_table(
        "family_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 120", name="ck_family_groups_name_length"),
        sa.CheckConstraint("name = btrim(name)", name="ck_family_groups_name_trimmed"),
        sa.PrimaryKeyConstraint("id", name="pk_family_groups"),
        sa.UniqueConstraint("name", name="uq_family_groups_name"),
    )
    op.create_index("ix_family_groups_created_by_user_id", "family_groups", ["created_by_user_id"], unique=False)
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient_user_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("deduplication_key", sa.String(length=160), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.UUID(), nullable=True),
        sa.Column("last_error", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "notification_type IN ('photo_shared', 'cleaning_due', 'shopping_added')",
            name="ck_notification_outbox_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'sent', 'failed')", name="ck_notification_outbox_status"
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_notification_outbox_attempt_count"),
        sa.PrimaryKeyConstraint("id", name="pk_notification_outbox"),
        sa.UniqueConstraint("recipient_user_id", "deduplication_key", name="uq_notification_outbox_recipient_dedupe"),
    )
    op.create_index("ix_notification_outbox_pending", "notification_outbox", ["status", "available_at"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "notification_type IN ('photo_shared', 'cleaning_due', 'shopping_added')",
            name="ck_notification_preferences_type",
        ),
        sa.PrimaryKeyConstraint("user_id", "notification_type", name="pk_notification_preferences"),
    )
    op.create_table(
        "photo_activity_states",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("seen_through_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seen_through_event_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="pk_photo_activity_states"),
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_username", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("lifecycle_state", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("trashed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trashed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(lifecycle_state = 'active' AND trashed_at IS NULL AND trashed_by_user_id IS NULL AND purge_after IS NULL AND purge_requested_at IS NULL) OR (lifecycle_state = 'trashed' AND trashed_at IS NOT NULL AND trashed_by_user_id IS NOT NULL AND purge_after IS NOT NULL AND purge_requested_at IS NULL) OR (lifecycle_state = 'purge_pending' AND trashed_at IS NOT NULL AND trashed_by_user_id IS NOT NULL AND purge_after IS NOT NULL AND purge_requested_at IS NOT NULL)",
            name="ck_photos_lifecycle_fields",
        ),
        sa.CheckConstraint(
            "lifecycle_state IN ('active', 'trashed', 'purge_pending')", name="ck_photos_lifecycle_state"
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name="ck_photos_sha256_lower_hex"),
        sa.CheckConstraint(
            "(width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)", name="ck_photos_dimensions"
        ),
        sa.CheckConstraint("size_bytes > 0", name="ck_photos_size_bytes_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_photos"),
        sa.UniqueConstraint("storage_key", name="uq_photos_storage_key"),
        sa.UniqueConstraint("uploaded_by_user_id", "sha256", name="uq_photos_uploaded_by_user_id_sha256"),
    )
    op.create_index("ix_photos_lifecycle_purge_after", "photos", ["lifecycle_state", "purge_after"], unique=False)
    op.create_index(
        "ix_photos_original_filename_trgm",
        "photos",
        ["original_filename"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"original_filename": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_photos_sort_date_id",
        "photos",
        [sa.literal_column("coalesce(captured_at, uploaded_at) DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index("ix_photos_uploaded_by_user_id", "photos", ["uploaded_by_user_id"], unique=False)
    op.create_table(
        "upload_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'completed', 'canceled')", name="ck_upload_batches_status"),
        sa.PrimaryKeyConstraint("id", name="pk_upload_batches"),
    )
    op.create_index(
        "ix_upload_batches_owner_user_id_created_at",
        "upload_batches",
        ["owner_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name="ck_user_invitations_token_hash_lower_hex"),
        sa.CheckConstraint("username = lower(username)", name="ck_user_invitations_username_lowercase"),
        sa.PrimaryKeyConstraint("id", name="pk_user_invitations"),
        sa.UniqueConstraint("token_hash", name="uq_user_invitations_token_hash"),
    )
    op.create_index(
        "ix_user_invitations_created_at",
        "user_invitations",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "uq_user_invitations_pending_username",
        "user_invitations",
        ["username"],
        unique=True,
        postgresql_where=sa.text("used_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("csrf_token ~ '^[A-Za-z0-9_-]{43}$'", name="ck_user_sessions_csrf_token"),
        sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name="ck_user_sessions_token_hash_lower_hex"),
        sa.PrimaryKeyConstraint("id", name="pk_user_sessions"),
        sa.UniqueConstraint("token_hash", name="uq_user_sessions_token_hash"),
    )
    op.create_index("ix_user_sessions_user_id", "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "cleaning_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 120", name="ck_cleaning_tasks_name_length"),
        sa.CheckConstraint("interval_days BETWEEN 1 AND 3650", name="ck_cleaning_tasks_interval_days"),
        sa.CheckConstraint("name = btrim(name)", name="ck_cleaning_tasks_name_trimmed"),
        sa.PrimaryKeyConstraint("id", name="pk_cleaning_tasks"),
    )
    op.create_index("ix_cleaning_tasks_group_id_is_active", "cleaning_tasks", ["group_id", "is_active"], unique=False)
    op.create_table(
        "family_group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'member')", name="ck_family_group_members_role"),
        sa.PrimaryKeyConstraint("group_id", "user_id", name="pk_family_group_members"),
    )
    op.create_index("ix_family_group_members_user_id", "family_group_members", ["user_id"], unique=False)
    op.create_table(
        "family_group_membership_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('admin', 'member')", name="ck_group_membership_invitations_role"),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'canceled')", name="ck_group_membership_invitations_status"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_group_membership_invitations"),
    )
    op.create_index(
        "ix_group_membership_invitations_user_status",
        "family_group_membership_invitations",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_group_membership_invitations_pending",
        "family_group_membership_invitations",
        ["group_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "photo_activity_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("actor_username", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("event_type IN ('uploaded', 'shared')", name="ck_photo_activity_events_event_type"),
        sa.PrimaryKeyConstraint("id", name="pk_photo_activity_events"),
    )
    op.create_index(
        "ix_photo_activity_events_occurred_at_id",
        "photo_activity_events",
        [sa.literal_column("occurred_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index("ix_photo_activity_events_operation_id", "photo_activity_events", ["operation_id"], unique=False)
    op.create_index("ix_photo_activity_events_photo_id", "photo_activity_events", ["photo_id"], unique=False)
    op.create_table(
        "photo_derivatives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("kind IN ('thumbnail')", name="ck_photo_derivatives_kind"),
        sa.CheckConstraint("size_bytes > 0", name="ck_photo_derivatives_size_bytes_positive"),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_photo_derivatives_dimensions"),
        sa.PrimaryKeyConstraint("id", name="pk_photo_derivatives"),
        sa.UniqueConstraint("photo_id", "kind", name="uq_photo_derivatives_photo_id_kind"),
        sa.UniqueConstraint("storage_key", name="uq_photo_derivatives_storage_key"),
    )
    op.create_index("ix_photo_derivatives_photo_id", "photo_derivatives", ["photo_id"], unique=False)
    op.create_table(
        "photo_favorites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", "photo_id", name="pk_photo_favorites"),
    )
    op.create_index("ix_photo_favorites_photo_id", "photo_favorites", ["photo_id"], unique=False)
    op.create_table(
        "photo_metadata",
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("memo_updated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("memo_updated_by_username", sa.String(length=64), nullable=False),
        sa.Column("memo_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at_override", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("memo IS NULL OR char_length(memo) <= 2000", name="ck_photo_metadata_memo_length"),
        sa.CheckConstraint("version > 0", name="ck_photo_metadata_version_positive"),
        sa.PrimaryKeyConstraint("photo_id", name="pk_photo_metadata"),
    )
    op.create_index(
        "ix_photo_metadata_memo_trgm",
        "photo_metadata",
        ["memo"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"memo": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_photo_metadata_memo_updated_by_user_id", "photo_metadata", ["memo_updated_by_user_id"], unique=False
    )
    op.create_table(
        "photo_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_photo_shares"),
        sa.UniqueConstraint("photo_id", "group_id", name="uq_photo_shares_photo_id_group_id"),
    )
    op.create_index("ix_photo_shares_group_id_photo_id", "photo_shares", ["group_id", "photo_id"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_session_id", sa.UUID(), nullable=False),
        sa.Column("endpoint_hash", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh_key", sa.Text(), nullable=False),
        sa.Column("auth_key", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("locale IN ('en', 'ja')", name="ck_push_subscriptions_locale"),
        sa.CheckConstraint("failure_count >= 0", name="ck_push_subscriptions_failure_count"),
        sa.PrimaryKeyConstraint("id", name="pk_push_subscriptions"),
        sa.UniqueConstraint("endpoint_hash", name="uq_push_subscriptions_endpoint_hash"),
    )
    op.create_index("ix_push_subscriptions_user_id", "push_subscriptions", ["user_id"], unique=False)
    op.create_index("ix_push_subscriptions_user_session_id", "push_subscriptions", ["user_session_id"], unique=False)
    op.create_table(
        "shopping_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("purchased_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(purchased_by_user_id IS NULL AND purchased_at IS NULL) OR (purchased_by_user_id IS NOT NULL AND purchased_at IS NOT NULL)",
            name="ck_shopping_items_purchase_state",
        ),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 120", name="ck_shopping_items_name_length"),
        sa.CheckConstraint("name = btrim(name)", name="ck_shopping_items_name_trimmed"),
        sa.PrimaryKeyConstraint("id", name="pk_shopping_items"),
    )
    op.create_index(
        "ix_shopping_items_group_id_purchase_state",
        "shopping_items",
        ["group_id", "purchased_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "upload_batch_group_shares",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("batch_id", "group_id", name="pk_upload_batch_group_shares"),
    )
    op.create_table(
        "upload_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("declared_content_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("received_bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("photo_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'uploading', 'processing', 'succeeded', 'duplicate', 'failed')",
            name="ck_upload_items_status",
        ),
        sa.CheckConstraint(
            "received_bytes >= 0 AND received_bytes <= size_bytes", name="ck_upload_items_received_bytes"
        ),
        sa.CheckConstraint("size_bytes > 0", name="ck_upload_items_size_bytes_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_upload_items"),
        sa.UniqueConstraint("batch_id", "client_id", name="uq_upload_items_batch_id_client_id"),
    )
    op.create_index("ix_upload_items_batch_id", "upload_items", ["batch_id"], unique=False)
    op.create_table(
        "cleaning_completions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "completed_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_cleaning_completions"),
    )
    op.create_index(
        "ix_cleaning_completions_task_id_completed_at",
        "cleaning_completions",
        ["task_id", sa.literal_column("completed_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("outbox_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=128), nullable=True),
        sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name="ck_notification_deliveries_status"),
        sa.CheckConstraint("attempt_count >= 0", name="ck_notification_deliveries_attempt_count"),
        sa.PrimaryKeyConstraint("outbox_id", "subscription_id", name="pk_notification_deliveries"),
    )
    op.create_table(
        "photo_activity_event_groups",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("event_id", "group_id", name="pk_photo_activity_event_groups"),
    )
    op.create_index(
        "ix_photo_activity_event_groups_group_id", "photo_activity_event_groups", ["group_id", "event_id"], unique=False
    )

    # Add foreign keys after all tables exist, including the album/photo cycle.
    op.create_foreign_key(
        "fk_album_photos_album_id_albums", "album_photos", "albums", ["album_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_album_photos_photo_id_photos", "album_photos", "photos", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_albums_created_by_user_id_users", "albums", "users", ["created_by_user_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        "fk_albums_group_id_family_groups", "albums", "family_groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_albums_cover_album_photos",
        "albums",
        "album_photos",
        ["id", "cover_photo_id"],
        ["album_id", "photo_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_family_groups_created_by_user_id_users",
        "family_groups",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_notification_outbox_recipient_user_id_users",
        "notification_outbox",
        "users",
        ["recipient_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_notification_preferences_user_id_users",
        "notification_preferences",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photo_activity_states_user_id_users",
        "photo_activity_states",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photos_trashed_by_user_id_users", "photos", "users", ["trashed_by_user_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        "fk_photos_uploaded_by_user_id_users", "photos", "users", ["uploaded_by_user_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        "fk_upload_batches_owner_user_id_users",
        "upload_batches",
        "users",
        ["owner_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_user_invitations_created_by_user_id_users",
        "user_invitations",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_user_sessions_user_id_users", "user_sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_cleaning_tasks_created_by_user_id_users",
        "cleaning_tasks",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_cleaning_tasks_group_id_family_groups",
        "cleaning_tasks",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_family_group_members_group_id_family_groups",
        "family_group_members",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_family_group_members_user_id_users",
        "family_group_members",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_group_membership_invitations_group_id",
        "family_group_membership_invitations",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_group_membership_invitations_requested_by_user_id",
        "family_group_membership_invitations",
        "users",
        ["requested_by_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_group_membership_invitations_user_id",
        "family_group_membership_invitations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photo_activity_events_actor_user_id_users",
        "photo_activity_events",
        "users",
        ["actor_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_photo_activity_events_photo_id_photos",
        "photo_activity_events",
        "photos",
        ["photo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photo_derivatives_photo_id_photos", "photo_derivatives", "photos", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_photo_favorites_photo_id_photos", "photo_favorites", "photos", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_photo_favorites_user_id_users", "photo_favorites", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_photo_metadata_memo_updated_by_user_id_users",
        "photo_metadata",
        "users",
        ["memo_updated_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_photo_metadata_photo_id_photos", "photo_metadata", "photos", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_photo_shares_group_id_family_groups",
        "photo_shares",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photo_shares_photo_id_photos", "photo_shares", "photos", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_push_subscriptions_user_id_users", "push_subscriptions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_push_subscriptions_user_session_id_user_sessions",
        "push_subscriptions",
        "user_sessions",
        ["user_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_shopping_items_created_by_user_id_users",
        "shopping_items",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_shopping_items_group_id_family_groups",
        "shopping_items",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_shopping_items_purchased_by_user_id_users",
        "shopping_items",
        "users",
        ["purchased_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_upload_batch_group_shares_batch_id_upload_batches",
        "upload_batch_group_shares",
        "upload_batches",
        ["batch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_upload_batch_group_shares_group_id_family_groups",
        "upload_batch_group_shares",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_upload_items_batch_id_upload_batches",
        "upload_items",
        "upload_batches",
        ["batch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_upload_items_photo_id_photos", "upload_items", "photos", ["photo_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        "fk_cleaning_completions_completed_by_user_id_users",
        "cleaning_completions",
        "users",
        ["completed_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_cleaning_completions_task_id_cleaning_tasks",
        "cleaning_completions",
        "cleaning_tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_notification_deliveries_outbox_id_notification_outbox",
        "notification_deliveries",
        "notification_outbox",
        ["outbox_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_notification_deliveries_subscription_id_push_subscriptions",
        "notification_deliveries",
        "push_subscriptions",
        ["subscription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photo_activity_event_groups_event_id_photo_activity_events",
        "photo_activity_event_groups",
        "photo_activity_events",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_photo_activity_event_groups_group_id_family_groups",
        "photo_activity_event_groups",
        "family_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_photo_activity_event_groups_group_id", table_name="photo_activity_event_groups")
    op.drop_table("photo_activity_event_groups")
    op.drop_table("notification_deliveries")
    op.drop_index("ix_cleaning_completions_task_id_completed_at", table_name="cleaning_completions")
    op.drop_table("cleaning_completions")
    op.drop_index("ix_upload_items_batch_id", table_name="upload_items")
    op.drop_table("upload_items")
    op.drop_table("upload_batch_group_shares")
    op.drop_index("ix_shopping_items_group_id_purchase_state", table_name="shopping_items")
    op.drop_table("shopping_items")
    op.drop_index("ix_push_subscriptions_user_session_id", table_name="push_subscriptions")
    op.drop_index("ix_push_subscriptions_user_id", table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index("ix_photo_shares_group_id_photo_id", table_name="photo_shares")
    op.drop_table("photo_shares")
    op.drop_index("ix_photo_metadata_memo_updated_by_user_id", table_name="photo_metadata")
    op.drop_index(
        "ix_photo_metadata_memo_trgm",
        table_name="photo_metadata",
        postgresql_using="gin",
        postgresql_ops={"memo": "gin_trgm_ops"},
    )
    op.drop_table("photo_metadata")
    op.drop_index("ix_photo_favorites_photo_id", table_name="photo_favorites")
    op.drop_table("photo_favorites")
    op.drop_index("ix_photo_derivatives_photo_id", table_name="photo_derivatives")
    op.drop_table("photo_derivatives")
    op.drop_index("ix_photo_activity_events_photo_id", table_name="photo_activity_events")
    op.drop_index("ix_photo_activity_events_operation_id", table_name="photo_activity_events")
    op.drop_index("ix_photo_activity_events_occurred_at_id", table_name="photo_activity_events")
    op.drop_table("photo_activity_events")
    op.drop_index(
        "uq_group_membership_invitations_pending",
        table_name="family_group_membership_invitations",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_group_membership_invitations_user_status", table_name="family_group_membership_invitations")
    op.drop_table("family_group_membership_invitations")
    op.drop_index("ix_family_group_members_user_id", table_name="family_group_members")
    op.drop_table("family_group_members")
    op.drop_index("ix_cleaning_tasks_group_id_is_active", table_name="cleaning_tasks")
    op.drop_table("cleaning_tasks")
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(
        "uq_user_invitations_pending_username",
        table_name="user_invitations",
        postgresql_where=sa.text("used_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_index("ix_user_invitations_created_at", table_name="user_invitations")
    op.drop_table("user_invitations")
    op.drop_index("ix_upload_batches_owner_user_id_created_at", table_name="upload_batches")
    op.drop_table("upload_batches")
    op.drop_index("ix_photos_uploaded_by_user_id", table_name="photos")
    op.drop_index("ix_photos_sort_date_id", table_name="photos")
    op.drop_index(
        "ix_photos_original_filename_trgm",
        table_name="photos",
        postgresql_using="gin",
        postgresql_ops={"original_filename": "gin_trgm_ops"},
    )
    op.drop_index("ix_photos_lifecycle_purge_after", table_name="photos")
    op.drop_table("photos")
    op.drop_table("photo_activity_states")
    op.drop_table("notification_preferences")
    op.drop_index("ix_notification_outbox_pending", table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index("ix_family_groups_created_by_user_id", table_name="family_groups")
    op.drop_table("family_groups")
    op.drop_table("users")
    op.drop_index("ix_maintenance_runs_job_type_started_at", table_name="maintenance_runs")
    op.drop_table("maintenance_runs")
    op.drop_index("ix_albums_updated_at_id", table_name="albums")
    op.drop_index("ix_albums_group_id", table_name="albums")
    op.drop_index("ix_albums_created_by_user_id", table_name="albums")
    op.drop_table("albums")
    op.drop_index("ix_album_photos_photo_id", table_name="album_photos")
    op.drop_table("album_photos")
    op.drop_index("ix_administrative_audit_events_group_id_created_at", table_name="administrative_audit_events")
    op.drop_index("ix_administrative_audit_events_created_at_id", table_name="administrative_audit_events")
    op.drop_table("administrative_audit_events")
    # ### end Alembic commands ###
